services:
  bequest-db:
    build:
      dockerfile: ./build/db.Dockerfile
      context: .
    restart: "no"
    shm_size: "2gb"
    ports:
      - 7654:5432
    #depends_on:
      #log-db:
      #condition: service_healthy
    env_file:
      - ./db/.env
    environment:
      POSTGRES_HOST: logging
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
    networks:
      logging:
  log-db:
    build:
      dockerfile: ./build/log-db.Dockerfile
      context: .
    restart: "no"
    shm_size: "2gb"
    expose:
      - 5432
    ports:
      - 8765:5432
    env_file:
      - ./log-db/.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
    #volumes:
      #- data:/var/lib/postgresql/data
    networks:
      logging:
        #aliases:
          #- postgres17.docker
    #healthcheck:
      ##test: ["CMD", "psql", "-d", "country_market", "-c", "SELECT * FROM markets LIMIT 1;"]
      #interval: 6s
      #timeout: 6s
      #retries: 5

#volumes:
  #data:
    #name: data-postgis16-data
    #external: false

networks:
  logging: {}

